import './globals.css'
import { Inter } from 'next/font/google'
import ThemeRegistry from './ThemeRegistry'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children
}: any) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        display: 'flex',
        width: '100%'
      }}>
        <ThemeRegistry options={{ key: 'mui-theme' }}><main>{children}</main></ThemeRegistry>
      </body>
    </html>
  )
}